### PR TITLE
Fix Encoder.ipynb not found errors by renaming Test.ipynb to Encoder.…

### PR DESCRIPTION
**Pull request by ariellubonja**
Hi! I'm a JHU AMS Masters working w/ Prof. Randal Burns. Prof. Carey Priebe is my advisor. Am trying to convert your code into edgemap model

Minor fix:
In Python folder, the jupyter notebooks say "%run Encoder.ipynb", but this file does not exist in the repo. I searched for the function defn. and found it in Test.ipynb, so I renamed the file and now things seem to work fine, which seemed to be your original intention.

Wanted to make a PR instead of an Issue bcs. I've implemented the fix

Cheers!
Ariel

### CODE REVIEW

**Comment by cshen6** [comment]
Thank you Ariel!

@Xihan Qin ***@***.***> Take a look & see if it is correct?

**Comment by cshen6** [comment]
Ariel,

Upon another look, the code you are looking at is actually earlier ones that was made obsolete.

I reorganized the folder. The main function is under main/GraphEncoder.ipynb. 

The experiment functions is under experiment/Python. 

The older Jupiter ones are now marked obsolete (but still kept for reference). Let me know if you have any other question.

**Comment by ariellubonja** [comment]
Thank you for such a quick solution/reply!

I will be looking at your code and paper in the next few days. I might ask a couple questions, if that’s OK? :)



Happy Spring break!

Best,
Ariel

**Comment by cshen6** [comment]
Sure thing.
You can email me directly or leave an issue on github, either is fine.

**Pull request closed without merging**
